/* ⚔ Crowz-Plugins — Plugin manifest
   Add new builds here; the site picks them up automatically. */
const PLUGINS = [
    {
        id: "pvpcorex",
        file: "PVPCoreX-1.0.0.jar",
        name: "PVPCoreX",
        monogram: "PX",
        category: "pvp",
        tag: "Flagship",
        recent: true,
        blurb: "The PvP core we actually run: combat tags, duels, bounties, death chests and KOTH in one jar.",
        description: "PVPCoreX started as the plugin we wanted on our own server and grew into a full PvP ecosystem. It covers the whole loop — combat tagging, killstreaks with effects, ranked duels with ELO, bounties, instant-loot death chests and scheduled KOTH events. No bloat, no per-module downloads; one jar, a few configs, done.",
        features: ["Combat tagging & punishment", "Ranked duels with ELO", "Bounties", "Death chests (no owner lock)", "Killstreaks + kill effects", "KOTH events", "PvP stats & leaderboards"],
        version: "1.0.0",
        size: "31.2 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+ (Folia compatible)", "Vault (optional — money rewards)"],
        commands: ["/pvpcorex", "/pvpcorex reload", "/pvpcorex duel <player>", "/pvpcorex bounty <player> <amount>", "/pvpcorex stats"],
        baseDownloads: 12480
    },
    {
        id: "ultimatevoice",
        file: "UltimateVoice-1.0.0.jar",
        name: "UltimateVoice",
        monogram: "UV",
        category: "voice",
        tag: "Voice chat",
        recent: false,
        blurb: "Group voice chat, 1v1 calls and a friends list — wired straight into Simple Voice Chat.",
        description: "UltimateVoice turns Simple Voice Chat into a full voice ecosystem. Players get 1v1 calls, voice groups, a friends list with block options, call history and an animated GUI that actually feels good to use. Call records are persisted in SQLite or MySQL so nothing disappears on restart.",
        features: ["1v1 calls", "Voice groups", "Friends & block list", "Call history", "Animated GUI", "SQLite / MySQL storage"],
        version: "1.0.0",
        size: "21.9 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+", "Simple Voice Chat (server + client)"],
        commands: ["/voice", "/voice call <player>", "/voice group <name>", "/voice friends", "/voice block <player>"],
        baseDownloads: 8321
    },
    {
        id: "crowzanticheat",
        file: "CrowzCAnticheat.jar",
        name: "CrowzCAnticheat",
        monogram: "CC",
        category: "security",
        tag: "Anticheat",
        recent: false,
        blurb: "A lean anticheat that flags real cheaters without nuking your TPS or your honest players.",
        description: "CrowzCAnticheat was written after we got tired of anticheats that either did nothing or banned everyone with a bad ping. It focuses on the detections that matter — kill aura, movement and auto-clicker — with configurable thresholds and a staff alert queue instead of instant bans.",
        features: ["KillAura detection", "Flight & velocity checks", "Auto-clicker detection", "Staff alert queue", "Per-check toggles"],
        version: "1.0.0",
        size: "0.4 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+", "StaffModerationPlus (optional — freeze/inspect actions)"],
        commands: ["/cac alerts", "/cac check <player>", "/cac reload"],
        baseDownloads: 2144
    },
    {
        id: "crowzantivpn",
        file: "CrowzAntiVPN-1.0.0.jar",
        name: "CrowzAntiVPN",
        monogram: "AV",
        category: "security",
        tag: "Security",
        recent: false,
        blurb: "Kicks VPNs, proxies and ban evaders before they ever touch your world.",
        description: "The average server gets alt-accounted every week. CrowzAntiVPN checks incoming connections against known VPN, proxy and hosting ranges and stops them at the door. Staff IPs can be whitelisted, and everything is logged so you can see what was actually blocked.",
        features: ["VPN & proxy blocking", "Hosting-range checks", "Staff IP whitelist", "Connection logs"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/antivpn check <player>", "/antivpn whitelist <ip>", "/antivpn logs"],
        baseDownloads: 1905
    },
    {
        id: "crowzpvp",
        file: "crowzpvp-1.0.0.jar",
        name: "CrowzPVP",
        monogram: "CP",
        category: "pvp",
        tag: "PvP",
        recent: false,
        blurb: "A lean PvP companion — kits, combat tweaks and arena basics without the bloat.",
        description: "Not every server needs the full PvPCoreX stack. CrowzPVP is the lightweight version: loadout kits, a few combat quality-of-life tweaks and simple arena mechanics. It's what we recommend to smaller servers that just want fights to feel right.",
        features: ["Loadout kits", "Combat QoL tweaks", "Arena basics", "Death drops control"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/cpvp kit create <name>", "/cpvp kit give <player> <kit>", "/cpvp reload"],
        baseDownloads: 1120
    },
    {
        id: "crowzoptimizer",
        file: "CrowzOptimizer-1.0.0.jar",
        name: "CrowzOptimizer",
        monogram: "CZ",
        category: "utility",
        tag: "Performance",
        recent: true,
        blurb: "Squeezes TPS out of the stuff nobody wants to touch: chunk loads, hoppers, mob AI.",
        description: "Most lag on a server comes from a handful of repeat offenders — loaded chunks nobody visits, hoppers checking empty containers, mobs pathfinding across the map. CrowzOptimizer finds those and throttles them sensibly, with sane defaults and presets for common server types.",
        features: ["Chunk & entity pruning", "Hopper throttling", "Mob AI limits", "Performance presets", "TPS graph on demand"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+ (Folia compatible)"],
        commands: ["/optimizer stats", "/optimizer scan", "/optimizer preset <name>", "/optimizer reload"],
        baseDownloads: 2677
    },
    {
        id: "crowzperformance",
        file: "crowzperformance-1.0.0.jar",
        name: "CrowzPerformance",
        monogram: "PF",
        category: "utility",
        tag: "Performance",
        recent: false,
        blurb: "Fine-grained control over mob caps, redstone and entity processing for big servers.",
        description: "CrowzPerformance is the tuning kit for servers that already have a tick budget in mind. Per-region mob caps, redstone tick limits, entity despawn ranges — everything is exposed as numbers you can actually reason about, not sliders that say 'low, medium, high'.",
        features: ["Per-region entity caps", "Redstone tick limits", "Despawn range control", "Tick-time budget alerts"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+ (Folia compatible)"],
        commands: ["/cperf caps", "/cperf region <name> set <value>", "/cperf budget"],
        baseDownloads: 1330
    },
    {
        id: "armordurability",
        file: "crowz-armordurability-hud-1.0.0.jar",
        name: "ArmorDurability HUD",
        monogram: "AD",
        category: "utility",
        tag: "HUD",
        recent: false,
        blurb: "A clean on-screen durability HUD so you stop dying with broken gear.",
        description: "Small plugin, big quality of life. ArmorDurability HUD shows your armor's remaining durability on screen, with colors that shift as things get dangerous. Position, size and thresholds are all configurable — no more guessing mid-fight.",
        features: ["On-screen durability readout", "Color thresholds", "Position & scale presets", "Per-player settings"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/durability", "/durability pos <corner>", "/durability toggle"],
        baseDownloads: 989
    },
    {
        id: "enclavejoinandquit",
        file: "EnclaveJoinAndQuit-1.0.0.jar",
        name: "EnclaveJoinAndQuit",
        monogram: "JQ",
        category: "core",
        tag: "Join messages",
        recent: false,
        blurb: "Join and quit messages with titles, sounds, and a separate message for first-timers.",
        description: "The first seconds of a player's session set the tone for the server. EnclaveJoinAndQuit handles the join and quit messages properly — titles, sounds, a distinct first-join message for new players, and MiniMessage support so the formatting matches your server's style.",
        features: ["Custom join/quit messages", "Title & sound support", "Separate first-join message", "MiniMessage formatting"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/jaq reload", "/jaq preview <join|quit>"],
        baseDownloads: 1440
    },
    {
        id: "enclaveshop",
        file: "EnclaveShop-1.0.0.jar",
        name: "EnclaveShop",
        monogram: "ES",
        category: "economy",
        tag: "Economy",
        recent: true,
        blurb: "Player shops with a GUI that doesn't make you tab through six menus to buy a pickaxe.",
        description: "EnclaveShop is the shop plugin we kept coming back to: a single GUI for browsing, buying and selling, chest shops for passive sales, and clean Vault integration. Stock, prices and per-player limits are all straightforward to configure.",
        features: ["GUI player shops", "Chest shops", "Buy & sell listings", "Vault integration", "Per-player shop limits"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+", "Vault + an economy provider (EssentialsX, CMI, etc.)"],
        commands: ["/shop", "/shop create <price>", "/shop remove", "/shop search <item>"],
        baseDownloads: 1880
    },
    {
        id: "enclavesmp",
        file: "EnclaveSMP-1.0.0.jar",
        name: "EnclaveSMP",
        monogram: "EM",
        category: "core",
        tag: "SMP",
        recent: false,
        blurb: "SMP essentials done once and done right: homes, spawn, warps, TPA and land protection.",
        description: "EnclaveSMP bundles the essentials every survival server ends up installing separately — homes, spawn, warps, TPA and land protection — into one plugin with one consistent command style and one config file. It's boring on purpose; it just works.",
        features: ["Homes & beds", "Spawn & warps", "TPA with requests", "Land protection", "Claim invites"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/home", "/sethome <name>", "/warp create <name>", "/tpa <player>", "/claim"],
        baseDownloads: 1710
    },
    {
        id: "everythingin1",
        file: "EverythingIn1-1.0.0.jar",
        name: "EverythingIn1",
        monogram: "E1",
        category: "utility",
        tag: "Grab-bag",
        recent: false,
        blurb: "A grab-bag of the features every server ends up asking for, in one tiny jar.",
        description: "Workbench access anywhere, sitting, signs that teleport, item frame protection, a /hat command, teleport back on death — the list of small features that slowly fills your plugins folder. EverythingIn1 puts the most-requested ones in one small jar with a single config.",
        features: ["Portable workbench", "Sitting & emotes", "Teleport signs", "Item frame protection", "/hat and friends"],
        version: "1.0.0",
        size: "0.2 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/e1", "/e1 bench", "/e1 hat", "/e1 toggle <feature>"],
        baseDownloads: 760
    },
    {
        id: "flowsmp",
        file: "FlowSMP-1.0.0.jar",
        name: "FlowSMP",
        monogram: "FS",
        category: "core",
        tag: "SMP",
        recent: true,
        blurb: "The full SMP kit — economy, warps, chat formatting and anti-grief in one place.",
        description: "FlowSMP was built for the type of server where players trade, build and actually care about their claims. It ships with a lightweight economy, player warps, chat formatting with ranks, and anti-grief protections — everything configured in one file that's actually readable.",
        features: ["Built-in economy", "Player warps", "Chat & rank formatting", "Anti-grief protection", "Payments & balancetop"],
        version: "1.0.0",
        size: "0.2 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+", "Vault (uses FlowSMP's own economy by default)"],
        commands: ["/flow balance", "/flow pay <player> <amount>", "/flow warp set <name>", "/flow top", "/flow reload"],
        baseDownloads: 1510
    },
    {
        id: "kaisclearlag",
        file: "KaisClearLag-1.0.0.jar",
        name: "KaisClearLag",
        monogram: "KL",
        category: "utility",
        tag: "Lag fix",
        recent: false,
        blurb: "Smart entity and item cleanup with warnings — not a blunt 'clear everything' button.",
        description: "A clear-lag plugin that just deletes everything every ten minutes fixes one problem and creates three more. KaisClearLag cleans the items and entities that actually linger, warns players before cleanup, and lets you whitelist the things you want to keep.",
        features: ["Lingering item cleanup", "Entity caps", "Pre-clear warnings", "Item & entity whitelists"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/clearlag now", "/clearlag stats", "/clearlag toggle <items|mobs>", "/clearlag reload"],
        baseDownloads: 1220
    },
    {
        id: "quitjoin",
        file: "QuitJoin-1.0.0.jar",
        name: "QuitJoin",
        monogram: "QJ",
        category: "core",
        tag: "Join messages",
        recent: false,
        blurb: "Join and quit messages with full MiniMessage support. That's it. That's the plugin.",
        description: "Some plugins should do one thing and get out of the way. QuitJoin formats join and quit messages with MiniMessage, supports per-player overrides, and has no features you'll never open. Under 30 KB, zero dependencies.",
        features: ["MiniMessage formatting", "Per-player overrides", "Group prefixes", "Zero dependencies"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/qj reload", "/qj message <player> <join|quit> <text>"],
        baseDownloads: 850
    },
    {
        id: "staffmoderationplus",
        file: "StaffModerationPlus-1.0.0.jar",
        name: "StaffModerationPlus",
        monogram: "SM",
        category: "security",
        tag: "Moderation",
        recent: false,
        blurb: "The moderation toolkit: vanish, freeze, inventory inspection and clean punishment records.",
        description: "StaffModerationPlus is what our own staff sit on all day. Vanish with per-staff visibility, freeze that actually stops movement, inventory inspection, chat moderation, and a punishment history that doesn't require a separate web panel to understand.",
        features: ["Vanish (per-staff visibility)", "Freeze & unfreeze", "Inventory inspection", "Chat moderation", "Punishment history"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+", "Vault (optional — permission-based actions)"],
        commands: ["/sm vanish", "/sm freeze <player>", "/sm inspect <player>", "/sm history <player>", "/sm reload"],
        baseDownloads: 2030
    },
    {
        id: "ultimateteam",
        file: "UltimateTeam-1.0.0.jar",
        name: "UltimateTeam",
        monogram: "UT",
        category: "core",
        tag: "Teams",
        recent: false,
        blurb: "Teams done right: team chat, friendly-fire control and teleport shortcuts.",
        description: "UltimateTeam gives players a way to squad up without a wall of commands — create a team, get a team chat, toggle friendly fire per team and teleport between members. PvP servers can hook it into their own event systems via the API.",
        features: ["Team creation & invites", "Team chat channel", "Friendly-fire control", "Team teleports", "PvP API hooks"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/team create <name>", "/team invite <player>", "/team chat", "/team ff <on|off>", "/team tp <member>"],
        baseDownloads: 1170
    },
    {
        id: "v0auth",
        file: "v0Auth-1.0.0.jar",
        name: "v0Auth",
        monogram: "0A",
        category: "security",
        tag: "Auth",
        recent: false,
        blurb: "Straightforward password auth with session tokens and brute-force protection.",
        description: "v0Auth does one job: keeps accounts tied to the people who own them. Password registration and login, session tokens so players don't log in every time they join, and lockout protection for brute-force attempts. Config is a handful of lines.",
        features: ["Password registration & login", "Session tokens", "Brute-force lockout", "IP-based notifications"],
        version: "1.0.0",
        size: "0.1 MB",
        paper: "Paper 1.21+",
        updated: "Aug 2026",
        requiresLicense: true,
        requirements: ["Java 21", "Paper 1.21+"],
        commands: ["/register <password> <password>", "/login <password>", "/changepassword <old> <new>"],
        baseDownloads: 1760
    }
];
